"""added streams fields to spotify_charts

Revision ID: 110233bfd37f
Revises: 9be7a5f8c123
Create Date: 2025-03-31 17:30:01.167842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110233bfd37f'
down_revision: Union[str, None] = '9be7a5f8c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_charts', sa.Column('streams', sa.BigInteger(), nullable=False))
    op.add_column('spotify_charts', sa.Column('total_streams', sa.BigInteger(), nullable=False))
    op.add_column('spotify_charts', sa.Column('days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_charts', 'days')
    op.drop_column('spotify_charts', 'total_streams')
    op.drop_column('spotify_charts', 'streams')
    # ### end Alembic commands ###
