"""Add sp_track and features JSONB fields to song table

Revision ID: 4e5431f34ac3
Revises: 
Create Date: 2025-03-23 20:40:43.392516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e5431f34ac3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('sp_track', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('song', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'features')
    op.drop_column('song', 'sp_track')
    # ### end Alembic commands ###
