"""Added mbids, Artist_stats, Country, Artist_charts

Revision ID: 8cca614f4912
Revises: 4e5431f34ac3
Create Date: 2025-03-26 20:59:37.037652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cca614f4912'
down_revision: Union[str, None] = '4e5431f34ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('artist_charts',
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.spotify_id'], ),
    sa.ForeignKeyConstraint(['country_code'], ['country.country_code'], ),
    sa.PrimaryKeyConstraint('artist_id', 'country_code', 'date'),
    sa.UniqueConstraint('artist_id', 'country_code', 'date', name='uq_artist_charts')
    )
    op.create_table('artist_stats',
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_streams', sa.BigInteger(), nullable=True),
    sa.Column('daily_streams', sa.Integer(), nullable=True),
    sa.Column('listeners', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.spotify_id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'date'),
    sa.UniqueConstraint('artist_id', 'date', name='uq_artists_stats')
    )
    op.add_column('artist', sa.Column('sp_artist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('artist', sa.Column('mbid', sa.String(), nullable=True))
    op.add_column('song', sa.Column('mbid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'mbid')
    op.drop_column('artist', 'mbid')
    op.drop_column('artist', 'sp_artist')
    op.drop_table('artist_stats')
    op.drop_table('artist_charts')
    op.drop_table('country')
    # ### end Alembic commands ###
