"""Add spotify_charts table

Revision ID: 9be7a5f8c123
Revises: 8cca614f4912
Create Date: 2025-03-31 10:30:45.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be7a5f8c123'
down_revision: Union[str, None] = '8cca614f4912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_charts',
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['country.country_code'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'country_code', 'date'),
    sa.UniqueConstraint('song_id', 'country_code', 'date', name='uq_spotify_charts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_charts')
    # ### end Alembic commands ###